### ISSUE TITLE
Inversed Eye for password displaying

### ISSUE THREAD

**Issue by mmby85** [arpitBhalla/react-mui-auth-page#1]
Hi,

Great work, i just suggest you to change the eye toggling for password it is inversed ^^ 

Good luck,

**Comment by arpitBhalla** [comment]
@mmby85 For sure, thanks you liked it...

**Comment by arpitBhalla** [comment]
@mmby85 For sure, thanks you liked it...

**Comment by arpitBhalla** [comment]
@mmby85 For sure.
